name: Phra Nakorn Living
favicon: null
layout_spectrum: 0.34763397206552327
typography_spectrum: 0.735664535081014
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010000'
    - '#b6dfeb'
    - '#6f5d35'
    - '#db7400'
    - '#ffd23d'
  brandStrength: 0.6875
  lightness: 0.9256865074858069
  saturation: 0.18154941592365503
  rhythmicContrast: 0.5844430692959577
purpose: []
