name: Phra Nakorn Living
favicon: null
layout_spectrum: 0.34763397206552327
typography_spectrum: 0.735664535081014
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.9866240550763905
  lightness: 0.9256865074858069
  saturation: 0.18154941592365503
  rhythmicContrast: 0.5844430692959577
purpose: []
